packages:
  - name: default
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      DATABASE: "${DATABASE}"
    actions:
      - name: findAll 
        runtime: nodejs:default
environment:
  DATABASE: "${DATABASE}"
  DATABASE_URL: "${DATABASE_URL}"        